spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/healthful;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # or create
    properties:
      hibernate:
        #        show_sql: true 운영 환경에서는 system.out.으로 찍으면 안됨
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: C:/productImages/
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace